#! /bin/sh

killall polybar picom

pgrep -x sxhkd > /dev/null || sxhkd &

polybar example &
picom --experimental-backend &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap		10
bspc config top_padding		15
bspc config bottom_padding	30
bspc config left_padding	 5
bspc config right_padding	 5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^4' follow=off focus=off
bspc rule -a Signal desktop='^4'
bspc rule -a libreoffice-startcenter desktop='^6'
bspc rule -a Zathura desktop='^6' state=tiled follow=on focus=on
bspc rule -a obs desktop='^7'
bspc rule -a Gimp desktop='^8' state=tiled follow=on
bspc rule -a Spotify desktop='^10' state=tiled follow=off
